### ISSUE TITLE
salesforce connector not working

### ISSUE THREAD

**Issue by jludvice** [syndesisio/connectors#56]
```
11:19:00.062 [main] INFO  o.a.camel.spring.SpringCamelContext - Apache Camel 2.19.0 (CamelContext: fuse-twitter-salesforce) started in 2.685 seconds
11:19:00.077 [main] INFO  o.a.c.c.s.CamelHttpTransportServlet - Initialized CamelHttpTransportServlet[name=CamelServlet, contextPath=]
11:19:00.219 [main] INFO  o.s.b.c.e.u.UndertowEmbeddedServletContainer - Undertow started on port(s) 8080 (http)
11:19:00.232 [main] INFO  io.syndesis.example.Application - Started Application in 12.104 seconds (JVM running for 17.14)
10:30:44.852 [HttpClient@105194717-23] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-fuse-twitter-salesforce-1-jof8i-35131-1498735134622-0-9 on ExchangeId: ID-fuse-twitter-salesforce-1-jof8i-35131-1498735134622-0-8). Exhausted after delivery attempt: 1 caught: org.apache.camel.component.salesforce.api.SalesforceException: Unexpected error {0:null} executing {PATCH:https://eu11.salesforce.com/services/data/v34.0/sobjects/Contact/TwitterScreenName__c/syndesis_talky}

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[flow1             ] [flow1             ] [twitter://timeline/mentions?delay=30000                                       ] [       150]
[flow1             ] [to1               ] [json:marshal                                                                  ] [         1]
[flow1             ] [to2               ] [atlas:mapping-step-2.json                                                     ] [        31]
[flow1             ] [to3               ] [json:marshal                                                                  ] [         0]
[flow1             ] [to4               ] [salesforce-upsert-contact                                                     ] [       103]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.camel.component.salesforce.api.SalesforceException: Unexpected error {0:null} executing {PATCH:https://eu11.salesforce.com/services/data/v34.0/sobjects/Contact/TwitterScreenName__c/syndesis_talky}
        at org.apache.camel.component.salesforce.internal.client.AbstractClientBase$1.onComplete(AbstractClientBase.java:179)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459)
        at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:540)
        at org.eclipse.jetty.client.HttpReceiver.responseFailure(HttpReceiver.java:431)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.failAndClose(HttpReceiverOverHTTP.java:341)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:310)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1418)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:196)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:143)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:130)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:116)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: HttpConnectionOverHTTP@76100a8(l:/10.1.10.67:54420 <-> r:eu11.salesforce.com/85.222.137.149:443,closed=false)=>HttpChannelOverHTTP@7d28f7d8(exchange=HttpExchange@79177ca5 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@3c15fde3(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@37cf140b{s=START}],recv=HttpReceiverOverHTTP@d63a31d(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]<-DecryptedEndPoint@4f531440{eu11.salesforce.com/85.222.137.149:443<->/10.1.10.67:54420,OPEN,fill=-,flush=-,to=342310021/0}->HttpConnectionOverHTTP@76100a8(l:/10.1.10.67:54420 <-> r:eu11.salesforce.com/85.222.137.149:443,closed=false)=>HttpChannelOverHTTP@7d28f7d8(exchange=HttpExchange@79177ca5 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@3c15fde3(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@37cf140b{s=START}],recv=HttpReceiverOverHTTP@d63a31d(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]->SocketChannelEndPoint@5c3a02ac{eu11.salesforce.com/85.222.137.149:443<->/10.1.10.67:54420,ISHUT,fill=-,flush=-,to=95/0}{io=0/0,kio=0,kro=1}->SslConnection@139a3a6c{NEED_WRAP,eio=-1/-1,di=-1}=>HttpConnectionOverHTTP@76100a8(l:/10.1.10.67:54420 <-> r:eu11.salesforce.com/85.222.137.149:443,closed=false)=>HttpChannelOverHTTP@7d28f7d8(exchange=HttpExchange@79177ca5 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@3c15fde3(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@37cf140b{s=START}],recv=HttpReceiverOverHTTP@d63a31d(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
        ... 20 common frames omitted
```

**Comment by davsclaus** [comment]
This is a bit long time so lets close this as its assuming working now
